/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chair.gltf 
Author: MaX3Dd (https://sketchfab.com/MaX3Dd)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/armchair-4f7d3af4c3fe40569983a894b7140904
Title: Armchair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./models/chair.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.armchair_armchair_0.geometry}
          material={materials.armchair}
          position={[0, 20.791, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/chair.gltf");
